apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 8000      # Внутренний порт сервиса (выбран 8000 как свободный)
      targetPort: 80  # Порт контейнера Nginx
